### ISSUE TITLE
Would be handy if this worked with the Builder field

### ISSUE THREAD

**Issue by smongey** [sylvainjule/kirby-imageboxes#4]
I’m get a `Cannot convert undefined or null to object` error when I try to save this when using it within a builder field.

Not sure if this is a more of a Builder plugin issue. 😬

**Comment by sylvainjule** [comment]
I have absolutely no clue what could be causing the issue, I can reproduce but the outputted value by the imageboxes field is fine, it is stored properly by the panel in Local Storage, what happens next does depend on the field anymore.

Closing this, it's probably builder-related but I've lost track of its latest changes so I wouldn't know where to look. Please open an issue there I'd be happy to help Tim debug if needed.
